# Generated by Django 3.1.6 on 2021-02-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbsposts',
            old_name='display_level',
            new_name='department',
        ),
    ]
