# Generated by Django 3.1.6 on 2021-02-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210211_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbsreply',
            name='is_reply',
            field=models.BooleanField(default=True),
        ),
    ]
