# Generated by Django 3.1.6 on 2021-02-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_bbsreply_is_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbsreply',
            name='is_reply',
        ),
        migrations.AddField(
            model_name='bbsposts',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
