# Generated by Django 3.2.8 on 2021-10-13 10:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='media/profilePics/default.jpg', upload_to='media/profilePics'),
        ),
    ]
