# Generated by Django 3.1.6 on 2021-02-16 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocked_in', models.BooleanField(default=False)),
                ('time_in', models.DateTimeField(blank=True)),
                ('time_out', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTimeClock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
