# Generated by Django 3.1.6 on 2021-02-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usertimemanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimemanagement',
            name='total',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
