# Generated by Django 3.1.6 on 2021-02-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usertimemanagement_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimemanagement',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertimemanagement',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertimemanagement',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
