# Generated by Django 3.1.6 on 2021-02-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210215_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimemanagement',
            name='total',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
