# Generated by Django 3.1.6 on 2021-02-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210215_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimemanagement',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
