# Generated by Django 3.1.6 on 2021-02-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210217_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimemanagement',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertimemanagement',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
